In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
% matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [5]:
dataset = pd.read_csv('WorldCupMatches.csv')
dataset

Year              Datetime              Stage  \
0     1930.0  13 Jul 1930 - 15:00             Group 1   
1     1930.0  13 Jul 1930 - 15:00             Group 4   
2     1930.0  14 Jul 1930 - 12:45             Group 2   
3     1930.0  14 Jul 1930 - 14:50             Group 3   
4     1930.0  15 Jul 1930 - 16:00             Group 1   
5     1930.0  16 Jul 1930 - 14:45             Group 1   
6     1930.0  17 Jul 1930 - 12:45             Group 2   
7     1930.0  17 Jul 1930 - 14:45             Group 4   
8     1930.0  18 Jul 1930 - 14:30             Group 3   
9     1930.0  19 Jul 1930 - 12:50             Group 1   
10    1930.0  19 Jul 1930 - 15:00             Group 1   
11    1930.0  20 Jul 1930 - 13:00             Group 2   
12    1930.0  20 Jul 1930 - 15:00             Group 4   
13    1930.0  21 Jul 1930 - 14:50             Group 3   
14    1930.0  22 Jul 1930 - 14:45             Group 1   
15    1930.0  26 Jul 1930 - 14:45         Semi-finals   
16    1930.0  27 Jul 1930 - 14:45         Semi-finals   
17    1930.0  30 Jul 1930 - 14:15               Final   
18    1934.0  27 May 1934 - 16:30   Preliminary round   
19    1934.0  27 May 1934 - 16:30   Preliminary round   
20    1934.0  27 May 1934 - 16:30   Preliminary round   
21    1934.0  27 May 1934 - 16:30   Preliminary round   
22    1934.0  27 May 1934 - 16:30   Preliminary round   
23    1934.0  27 May 1934 - 16:30   Preliminary round   
24    1934.0  27 May 1934 - 16:30   Preliminary round   
25    1934.0  27 May 1934 - 16:30   Preliminary round   
26    1934.0  31 May 1934 - 16:30      Quarter-finals   
27    1934.0  31 May 1934 - 16:30      Quarter-finals   
28    1934.0  31 May 1934 - 16:30      Quarter-finals   
29    1934.0  31 May 1934 - 16:30      Quarter-finals   
...      ...                   ...                ...   
4542     NaN                   NaN                NaN   
4543     NaN                   NaN                NaN   
4544     NaN                   NaN                NaN   
4545     NaN                   NaN                NaN   
4546     NaN                   NaN                NaN   
4547     NaN                   NaN                NaN   
4548     NaN                   NaN                NaN   
4549     NaN                   NaN                NaN   
4550     NaN                   NaN                NaN   
4551     NaN                   NaN                NaN   
4552     NaN                   NaN                NaN   
4553     NaN                   NaN                NaN   
4554     NaN                   NaN                NaN   
4555     NaN                   NaN                NaN   
4556     NaN                   NaN                NaN   
4557     NaN                   NaN                NaN   
4558     NaN                   NaN                NaN   
4559     NaN                   NaN                NaN   
4560     NaN                   NaN                NaN   
4561     NaN                   NaN                NaN   
4562     NaN                   NaN                NaN   
4563     NaN                   NaN                NaN   
4564     NaN                   NaN                NaN   
4565     NaN                   NaN                NaN   
4566     NaN                   NaN                NaN   
4567     NaN                   NaN                NaN   
4568     NaN                   NaN                NaN   
4569     NaN                   NaN                NaN   
4570     NaN                   NaN                NaN   
4571     NaN                   NaN                NaN   

                      Stadium         City  Home Team Name  Home Team Goals  \
0                     Pocitos  Montevideo           France              4.0   
1              Parque Central  Montevideo              USA              3.0   
2              Parque Central  Montevideo       Yugoslavia              2.0   
3                     Pocitos  Montevideo          Romania              3.0   
4              Parque Central  Montevideo        Argentina              1.0   

In [6]:
dataset.shape

(4572, 20)

In [7]:
dataset.index

RangeIndex(start=0, stop=4572, step=1)

In [8]:
#first 5 lines
dataset.head()

Year              Datetime    Stage         Stadium         City  \
0  1930.0  13 Jul 1930 - 15:00   Group 1         Pocitos  Montevideo    
1  1930.0  13 Jul 1930 - 15:00   Group 4  Parque Central  Montevideo    
2  1930.0  14 Jul 1930 - 12:45   Group 2  Parque Central  Montevideo    
3  1930.0  14 Jul 1930 - 14:50   Group 3         Pocitos  Montevideo    
4  1930.0  15 Jul 1930 - 16:00   Group 1  Parque Central  Montevideo    

  Home Team Name  Home Team Goals  Away Team Goals Away Team Name  \
0         France              4.0              1.0         Mexico   
1            USA              3.0              0.0        Belgium   
2     Yugoslavia              2.0              1.0         Brazil   
3        Romania              3.0              1.0           Peru   
4      Argentina              1.0              0.0         France   

  Win conditions  Attendance  Half-time Home Goals  Half-time Away Goals  \
0                     4444.0                   3.0                   0.0   
1                    18346.0                   2.0                   0.0   
2                    24059.0                   2.0                   0.0   
3                     2549.0                   1.0                   0.0   
4                    23409.0                   0.0                   0.0   

                  Referee               Assistant 1  \
0  LOMBARDI Domingo (URU)     CRISTOPHE Henry (BEL)   
1       MACIAS Jose (ARG)  MATEUCCI Francisco (URU)   
2     TEJADA Anibal (URU)   VALLARINO Ricardo (URU)   
3   WARNKEN Alberto (CHI)       LANGENUS Jean (BEL)   
4     REGO Gilberto (BRA)      SAUCEDO Ulises (BOL)   

                  Assistant 2  RoundID  MatchID Home Team Initials  \
0         REGO Gilberto (BRA)    201.0   1096.0                FRA   
1       WARNKEN Alberto (CHI)    201.0   1090.0                USA   
2         BALWAY Thomas (FRA)    201.0   1093.0                YUG   
3    MATEUCCI Francisco (URU)    201.0   1098.0                ROU   
4  RADULESCU Constantin (ROU)    201.0   1085.0                ARG   

  Away Team Initials  
0                MEX  
1                BEL  
2                BRA  
3                PER  
4                FRA

In [9]:
dataset.columns

Index(['Year', 'Datetime', 'Stage', 'Stadium', 'City', 'Home Team Name',
       'Home Team Goals', 'Away Team Goals', 'Away Team Name',
       'Win conditions', 'Attendance', 'Half-time Home Goals',
       'Half-time Away Goals', 'Referee', 'Assistant 1', 'Assistant 2',
       'RoundID', 'MatchID', 'Home Team Initials', 'Away Team Initials'],
      dtype='object')

In [50]:
dataset.info

<bound method DataFrame.info of        Year              Datetime                     Stage  \
0    1930.0  13 Jul 1930 - 15:00                    Group 1   
1    1930.0  13 Jul 1930 - 15:00                    Group 4   
2    1930.0  14 Jul 1930 - 12:45                    Group 2   
3    1930.0  14 Jul 1930 - 14:50                    Group 3   
4    1930.0  15 Jul 1930 - 16:00                    Group 1   
5    1930.0  16 Jul 1930 - 14:45                    Group 1   
6    1930.0  17 Jul 1930 - 12:45                    Group 2   
7    1930.0  17 Jul 1930 - 14:45                    Group 4   
8    1930.0  18 Jul 1930 - 14:30                    Group 3   
9    1930.0  19 Jul 1930 - 12:50                    Group 1   
10   1930.0  19 Jul 1930 - 15:00                    Group 1   
11   1930.0  20 Jul 1930 - 13:00                    Group 2   
12   1930.0  20 Jul 1930 - 15:00                    Group 4   
13   1930.0  21 Jul 1930 - 14:50                    Group 3   
14   1930.0  22 Jul 193

In [51]:
#knowing null value set
dataset.isnull().sum()

Year                    0
Datetime                0
Stage                   0
Stadium                 0
City                    0
Home Team Name          0
Home Team Goals         0
Away Team Goals         0
Away Team Name          0
Win conditions          0
Attendance              0
Half-time Home Goals    0
Half-time Away Goals    0
Referee                 0
Assistant 1             0
Assistant 2             0
RoundID                 0
MatchID                 0
Home Team Initials      0
Away Team Initials      0
dtype: int64

In [52]:
'''
1st method:dropna:
1. deletes a row if it has a null value for a particular feature
2. deletes a particular column if it has more than 75% missing values
'''
#advised only if enough samples in dataset exist
dataset.dropna(inplace =True)

In [53]:
dataset.isnull().sum()

Year                    0
Datetime                0
Stage                   0
Stadium                 0
City                    0
Home Team Name          0
Home Team Goals         0
Away Team Goals         0
Away Team Name          0
Win conditions          0
Attendance              0
Half-time Home Goals    0
Half-time Away Goals    0
Referee                 0
Assistant 1             0
Assistant 2             0
RoundID                 0
MatchID                 0
Home Team Initials      0
Away Team Initials      0
dtype: int64

In [54]:
dataset.shape

(850, 20)

In [55]:
'''
method 2 of removing NaN:
replace it with mean, median or mode
'''
dataset['Year'].mean()

1985.0211764705882

In [56]:
#viewing last 5 items
dataset['Year'].tail()

847    2014.0
848    2014.0
849    2014.0
850    2014.0
851    2014.0
Name: Year, dtype: float64

In [57]:
#replacing
dataset['Year'].replace(np.NaN,dataset['Year'].mean()).tail()

847    2014.0
848    2014.0
849    2014.0
850    2014.0
851    2014.0
Name: Year, dtype: float64

In [173]:
#as ML uses mathematical equations, set the catagorical values also
datanew = pd.read_csv('Data.csv')
datanew

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [174]:
#so we have to change yes and no to 0 & 1
datanew.Purchased.replace(('Yes','No'), (1, 0), inplace=True)
datanew

Country   Age   Salary  Purchased
0   France  44.0  72000.0          0
1    Spain  27.0  48000.0          1
2  Germany  30.0  54000.0          0
3    Spain  38.0  61000.0          0
4  Germany  40.0      NaN          1
5   France  35.0  58000.0          1
6    Spain   NaN  52000.0          0
7   France  48.0  79000.0          1
8  Germany  50.0  83000.0          0
9   France  37.0  67000.0          1

In [175]:
X = datanew.iloc[:, :-1].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [176]:
datanew.dropna(inplace=True)

In [177]:
datanew.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

In [178]:

datanew

Country   Age   Salary  Purchased
0   France  44.0  72000.0          0
1    Spain  27.0  48000.0          1
2  Germany  30.0  54000.0          0
3    Spain  38.0  61000.0          0
5   France  35.0  58000.0          1
7   France  48.0  79000.0          1
8  Germany  50.0  83000.0          0
9   France  37.0  67000.0          1

In [179]:
X[:,0]

array(['France', 'Spain', 'Germany', 'Spain', 'Germany', 'France',
       'Spain', 'France', 'Germany', 'France'], dtype=object)

In [180]:
'''
working on catagorical values
so we encode the catagorial variables
catagorical to numerical data we use LabelEncoder() class
from pre processing lib
'''
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()


In [181]:
#removing any NaN values
X = datanew.iloc[:,:-1].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['France', 35.0, 58000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [182]:
#converting to catagorical
X[:,0] = label_encoder.fit_transform(X[:,0])
X=np.array(X,dtype='int32')

In [183]:
#0,1,2 are catagorical values of resp. countries
X

array([[    0,    44, 72000],
       [    2,    27, 48000],
       [    1,    30, 54000],
       [    2,    38, 61000],
       [    0,    35, 58000],
       [    0,    48, 79000],
       [    1,    50, 83000],
       [    0,    37, 67000]])

In [184]:
#another method
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features=[0])

In [185]:
x = onehotencoder.fit_transform(X)
print(x)

  (0, 0)	1.0
  (1, 2)	1.0
  (2, 1)	1.0
  (3, 2)	1.0
  (4, 0)	1.0
  (5, 0)	1.0
  (6, 1)	1.0
  (7, 0)	1.0
  (0, 3)	44.0
  (0, 4)	72000.0
  (1, 3)	27.0
  (1, 4)	48000.0
  (2, 3)	30.0
  (2, 4)	54000.0
  (3, 3)	38.0
  (3, 4)	61000.0
  (4, 3)	35.0
  (4, 4)	58000.0
  (5, 3)	48.0
  (5, 4)	79000.0
  (6, 3)	50.0
  (6, 4)	83000.0
  (7, 3)	37.0
  (7, 4)	67000.0


In [186]:
datanew

Country   Age   Salary  Purchased
0   France  44.0  72000.0          0
1    Spain  27.0  48000.0          1
2  Germany  30.0  54000.0          0
3    Spain  38.0  61000.0          0
5   France  35.0  58000.0          1
7   France  48.0  79000.0          1
8  Germany  50.0  83000.0          0
9   France  37.0  67000.0          1

In [187]:
dummy = pd.get_dummies(datanew['Country'])
dummy

France  Germany  Spain
0       1        0      0
1       0        0      1
2       0        1      0
3       0        0      1
5       1        0      0
7       1        0      0
8       0        1      0
9       1        0      0

In [188]:
datanew = pd.concat([datanew,dummy],axis=1)
datanew

Country   Age   Salary  Purchased  France  Germany  Spain
0   France  44.0  72000.0          0       1        0      0
1    Spain  27.0  48000.0          1       0        0      1
2  Germany  30.0  54000.0          0       0        1      0
3    Spain  38.0  61000.0          0       0        0      1
5   France  35.0  58000.0          1       1        0      0
7   France  48.0  79000.0          1       1        0      0
8  Germany  50.0  83000.0          0       0        1      0
9   France  37.0  67000.0          1       1        0      0

In [190]:
datanew = datanew.drop(['Country'],axis = 1)
datanew

Age   Salary  Purchased  France  Germany  Spain
0  44.0  72000.0          0       1        0      0
1  27.0  48000.0          1       0        0      1
2  30.0  54000.0          0       0        1      0
3  38.0  61000.0          0       0        0      1
5  35.0  58000.0          1       1        0      0
7  48.0  79000.0          1       1        0      0
8  50.0  83000.0          0       0        1      0
9  37.0  67000.0          1       1        0      0

In [208]:
datanew.dropna(inplace = True)
y = datanew.iloc[:,2].values
y

array([0, 1, 0, 0, 1, 1, 0, 1], dtype=int64)

In [226]:
 #from sklearn.cross_validation import train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)
X_train

array([[    2,    38, 61000],
       [    0,    37, 67000],
       [    1,    50, 83000],
       [    2,    27, 48000],
       [    0,    35, 58000],
       [    0,    44, 72000]])

In [227]:
 X_test

array([[    0,    48, 79000],
       [    1,    30, 54000]])

In [228]:
y_train

array([0, 1, 0, 1, 1, 0], dtype=int64)